/* Aoife's School — Scriptable medium-widget bundle. GENERATED by
 * scripts/build-widget.mjs from js/model.js + js/plan/model.js +
 * js/plan/mday.js + scripts/widget-ui.js. NEVER edit this file by hand —
 * edit the sources and rebuild: node scripts/build-widget.mjs
 * build 802ed8eff2 */
(async () => {
/* ── js/model.js ── */
// Pure data model — no DOM, no storage. Imported by the app and by Node tests.
// The event shape and category keys are the v1 storage contract: DO NOT CHANGE.

const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
const S = 9;      // grid start hour (9am)
const E = 17;     // grid end hour (5pm)
const SPH = 66;   // screen pixels per hour
const PPH = 72;   // print pixels per hour (644px total — fits letter AND A4 landscape with headroom for up to ~110% print scale)

const CATS = {
  quran:   { label: 'Quran',                                  cls: 'q'  },
  ruhamah: { label: 'Ruhama — ELA/Math',                 cls: 'r'  },
  hala:    { label: 'Miss Hala — Arabic/Islamic Studies', cls: 'h' },
  barakot: { label: 'Barrington trip',                        cls: 'b'  },
  art:     { label: 'Art Class with Ayra',                    cls: 'a'  },
  other:   { label: 'Other',                                  cls: 'ot' },
};

function fmt(h) {
  const hh = Math.floor(h), mm = Math.round((h - hh) * 60), ap = hh >= 12 ? 'pm' : 'am';
  const h12 = hh > 12 ? hh - 12 : hh === 0 ? 12 : hh;
  return mm ? `${h12}:${String(mm).padStart(2, '0')}${ap}` : `${h12}${ap}`;
}

const snap = h => Math.round(h * 2) / 2;
const clampStart = (start, dur) => Math.max(S, Math.min(E - dur, start));
const clampEnd = (start, end) => Math.min(E, Math.max(start + 0.5, end));

// JS Date.getDay() (Sun=0) -> Mon-first index (Mon=0 ... Sun=6)
const todayIndex = jsDay => (jsDay + 6) % 7;

const esc = s => String(s).replace(/[&<>"']/g, c =>
  ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

function defEvents() {
  let n = 0;
  const uid = () => `e${++n}`;
  return [
    ...[0, 2, 4].map(d => ({ id: uid(), cat: 'quran', day: d, start: 10, end: 11, note: '', name: '' })),
    { id: uid(), cat: 'ruhamah', day: 0, start: 11, end: 13, note: '2-hr session', name: '' },
    { id: uid(), cat: 'ruhamah', day: 1, start: 11, end: 12, note: '', name: '' },
    { id: uid(), cat: 'ruhamah', day: 3, start: 11, end: 12, note: '', name: '' },
    { id: uid(), cat: 'ruhamah', day: 5, start: 11, end: 13, note: '2-hr session', name: '' },
    { id: uid(), cat: 'ruhamah', day: 6, start: 11, end: 13, note: 'Regular Sun — every other week at 10am', name: '' },
    ...[1, 2, 3].map(d => ({ id: uid(), cat: 'hala', day: d, start: 14, end: 16, note: '', name: '' })),
    { id: uid(), cat: 'barakot', day: 6, start: 9, end: 10, note: 'Mostly Sundays', name: 'Barrington trip' },
  ];
}

const maxIdNum = events =>
  events.reduce((mx, e) => Math.max(mx, parseInt(String(e.id).replace('e', ''), 10) || 0), 0);

const isValidEvent = e =>
  !!e && typeof e === 'object' && 'id' in e && 'cat' in e &&
  typeof e.day === 'number' && typeof e.start === 'number' && typeof e.end === 'number';
const sanitizeEvents = events => (Array.isArray(events) ? events.filter(isValidEvent) : []);

const serialize = ({ events, altSun, catLabels }) =>
  JSON.stringify({ events, altSun, catLabels });

const applyAltSun = (events, altSun) =>
  events.map(ev =>
    ev.cat === 'ruhamah' && ev.day === 6
      ? altSun
        ? { ...ev, start: 10, end: 12, note: 'Alt Sunday — Ruhamah at 10am' }
        : { ...ev, start: 11, end: 13, note: 'Regular Sun — every other week at 10am' }
      : ev
  );

/* ── js/plan/model.js ── */
// Planner pure model — no DOM, no storage. Companion to ../model.js.
// All dates are local 'YYYY-MM-DD' strings. Week walks are keyed by their
// Monday; time away is day-precise and lives in `plan.periods` (v2).

const d2s = d =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
const s2d = s => { const [y, m, d] = s.split('-').map(Number); return new Date(y, m - 1, d); };
const todayStr = () => d2s(new Date());
const addDays = (s, n) => { const d = s2d(s); d.setDate(d.getDate() + n); return d2s(d); };
const dayIdx = s => (s2d(s).getDay() + 6) % 7;           // Mon=0 … Sun=6
const mondayOf = s => addDays(s, -dayIdx(s));
const weeksBetween = (a, b) =>
  Math.round((s2d(mondayOf(b)) - s2d(mondayOf(a))) / 604800000);
// Round, don't floor: a DST boundary makes a "day" 23 or 25 hours long.
const daysBetween = (a, b) => Math.round((s2d(b) - s2d(a)) / 86400000);

// Monday parity of the 2-week parent cycle (which weeks are "work weeks").
const isOnWeek = (cycle, dateStr) =>
  ((weeksBetween(cycle.anchorMonday, dateStr) % 2) + 2) % 2 === 0;

// Day-precise duty: a Charlton work stretch runs Tue → Mon (7 days on, 7 off)
// from `dutyStart`. Dates before dutyStart must keep the same parity, hence the
// double modulo.
const DEFAULT_DUTY_START = '2026-08-11';
const isWorkDay = (cycle, dateStr) =>
  ((daysBetween(cycle?.dutyStart || DEFAULT_DUTY_START, dateStr) % 14) + 14) % 14 < 7;

// ── Time-away periods (day-precise; replaces the week map) ──
const PERIOD_TYPES = ['travel', 'off'];
const asPeriods = x => (Array.isArray(x) ? x : []);           // guard: non-array/missing -> none
const byPeriodStart = (a, b) =>
  a.start < b.start ? -1 : a.start > b.start ? 1 : a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
const sortPeriods = list => list.sort(byPeriodStart);

// The period covering this day, or null.
// OVERLAPS: `off` WINS over `travel` — an off day pauses everything, so it is
// the stronger claim and the safer default when two periods collide (the family
// would rather see a day off they meant to keep than schoolwork they cancelled).
// Among periods of the SAME type the first in sort order wins; the list is kept
// sorted by start (sanitizePlan + every state.js mutation), so that is the
// earliest start. Nothing here mutates or re-sorts `periods`.
const dayAway = (periods, dateStr) => {
  let hit = null;
  for (const p of asPeriods(periods)) {
    if (p.start > dateStr || dateStr > p.end) continue;
    if (!hit) { hit = p; }
    else if (hit.type !== 'off' && p.type === 'off') hit = p;
    if (hit.type === 'off') break;                            // nothing can outrank an off day
  }
  return hit;
};

function dayStatus(periods, dateStr) {
  const p = dayAway(periods, dateStr);
  if (!p) return { away: false };
  return {
    away: true, id: p.id, type: p.type, label: p.label || '',
    dayN: daysBetween(p.start, dateStr) + 1,
    total: daysBetween(p.start, p.end) + 1,
  };
}

const awayDaysInWeek = (periods, weekStart) => {
  let n = 0;
  for (let i = 0; i < 7; i++) if (dayAway(periods, addDays(weekStart, i))) n++;
  return n;
};

// School-days-worth of this week for one activity: a plain day is 1, an `off`
// day is 0, a travel day is worth whatever the activity's travel mode says.
function effectiveDaysInWeek(act, weekStart, periods) {
  const t = act?.travel || { mode: 'pause' };
  let n = 0;
  for (let i = 0; i < 7; i++) {
    const away = dayAway(periods, addDays(weekStart, i));
    if (!away) { n += 1; continue; }
    if (away.type === 'off') continue;                        // everything pauses
    if (t.mode === 'continue') n += 1;
    else if (t.mode === 'reduced') n += (t.factor ?? 0.5);
  }
  return n;
}

// ── Curricula & sessions ────────────────────────────────────
function sessionsCount(cur) {
  if (cur.pattern === 'tb-wb') return (cur.lessons || 0) * 2 + (cur.tests || 0);
  if (cur.lastUnit == null || cur.firstUnit == null) return 0;
  return Math.max(0, cur.lastUnit - cur.firstUnit + 1);
}

function sessionLabel(cur, i) {              // i = 0-based session index
  if (cur.pattern === 'tb-wb') {
    const L = (cur.lessons || 0) * 2;
    if (i < L) return `Lesson ${Math.floor(i / 2) + 1} · ${i % 2 ? 'workbook' : 'textbook'}`;
    return `Test ${i - L + 1}`;
  }
  const u = cur.firstUnit + i;
  return (cur.titles || {})[u] || `${cur.unitWord || 'Lesson'} ${u}`;
}

const nextSession = cur => {
  const n = sessionsCount(cur), d = cur.done || 0;
  return d >= n ? null : { index: d, label: sessionLabel(cur, d) };
};

// ── Category class tokens ───────────────────────────────────
// `cls` is interpolated RAW into class="…" attributes by every view, so it is
// whitelisted rather than escaped. Lives here (pure) so no view imports another.
const CLS = new Set(['q', 'r', 'h', 'b', 'a', 'ot', 'g', 's', 'j']);
const okCls = x => (CLS.has(x) ? x : 'ot');

// ── Subjects tab order (planner-v2.8, family feedback 2026-08-19) ──
// Fixed order: the top three (Singapore, LoE, Geography) are what Nabila
// needs day to day, then the core categories, then the rest. An id not in
// this list (a future activity) sorts after every known one, stable among
// THEMSELVES by the OLD status order (active/planned/parked/done/cancelled)
// — the rule this list replaces for everything it names.
const SUBJECT_ORDER = ['singapore', 'loe', 'geography', 'core-ruhamah',
  'core-hala', 'core-quran', 'core-art', 'science', 'jj', 'history', 'core-mama'];
const SUBJECT_STATUS_ORDER = { active: 0, planned: 1, parked: 2, done: 3, cancelled: 4 };
function compareSubjects(a, b) {
  const ia = SUBJECT_ORDER.indexOf(a?.id), ib = SUBJECT_ORDER.indexOf(b?.id);
  const ka = ia === -1 ? SUBJECT_ORDER.length : ia;
  const kb = ib === -1 ? SUBJECT_ORDER.length : ib;
  if (ka !== kb) return ka - kb;
  if (ia !== -1) return 0;    // both known: ids are unique, nothing left to break the tie
  return (SUBJECT_STATUS_ORDER[a?.status] ?? 9) - (SUBJECT_STATUS_ORDER[b?.status] ?? 9);
}

const currentCur = act => (act.chain || []).find(c => (c.done || 0) < sessionsCount(c)) || null;
const actTotal = act => (act.chain || []).reduce((s, c) => s + sessionsCount(c), 0);
const actDone = act => (act.chain || []).reduce((s, c) => s + Math.min(c.done || 0, sessionsCount(c)), 0);
const actRemaining = act => Math.max(0, actTotal(act) - actDone(act));

// ── Lesson-based totals (Subjects header: "2/60 lessons") ───
// A session count and a LESSON count differ for tb-wb chains: two sessions
// (textbook + workbook) make one lesson, and a chapter's Review sessions
// (`tests`) are teaching-order bookkeeping, not lessons — they are EXCLUDED
// from both numbers entirely, the same way a chapter test doesn't move a
// "lessons done" counter in real life. A simple chain (LoE) has no such split:
// each unit already IS a lesson, so it counts 1:1, same as actTotal/actDone.
function lessonTotals(act) {
  let done = 0, total = 0;
  for (const c of act?.chain || []) {
    if (!c || typeof c !== 'object') continue;
    if (c.pattern === 'tb-wb') {
      const lessons = Math.max(0, c.lessons || 0);
      const lessonSessions = lessons * 2;
      // Clamp to the lesson sessions BEFORE halving: review/test sessions
      // logged past lessons*2 must contribute 0, not a phantom half-lesson.
      const d = Math.min(Math.max(0, c.done || 0), lessonSessions);
      total += lessons;
      done += Math.min(Math.floor(d / 2) + (d % 2 ? 0.5 : 0), lessons);
    } else if (c.pattern === 'simple') {
      if (c.firstUnit == null || c.lastUnit == null) continue;
      const units = Math.max(0, c.lastUnit - c.firstUnit + 1);
      total += units;
      done += Math.min(Math.max(0, c.done || 0), units);
    }
  }
  return { done, total };
}

// ── Chapter timeline (Subjects 📅 Timeline) ─────────────────
// Row descriptors for a paced activity's chain, in teaching order.
// tb-wb chains (Singapore chapters) are one row each; simple chains (LoE books)
// split into BAND_SIZE-unit display bands so a 40-lesson book reads as
// milestones. Bands are DISPLAY ONLY — nothing stored changes shape, so band
// size can change later without any data migration.
const BAND_SIZE = 10;
function timelineRows(act) {
  const rows = [];
  // WALK_CAP is declared later in this file; fine at call time (module-scope
  // const, this function only runs post-evaluation). Same belt-and-braces
  // reasoning as WALK_CAP's own comment: a fat-fingered lastUnit (or a huge
  // hand-built chain) must never build 500k row objects and hang a tab.
  // Beyond the cap, per-row dates are computed from the visible rows only —
  // the projectFinish agreement holds for real curricula (≤~30 rows), not
  // for pathological spans.
  for (const c of act?.chain || []) {
    if (rows.length >= WALK_CAP) break;
    const total = sessionsCount(c);
    const done = Math.min(Math.max(0, c.done || 0), total);
    if (c.pattern === 'tb-wb') {
      rows.push({ key: c.id, chainId: c.id, label: c.name || c.id, sessions: total, done });
    } else {
      if (c.firstUnit == null || c.lastUnit == null) continue;
      const word = c.unitWord || 'Lesson';
      // Per-chain display band size (LoE ships 5-lesson bands while Singapore's
      // simple chains, if any, keep the default) — DISPLAY ONLY, same as
      // BAND_SIZE itself: nothing stored changes shape.
      const bandSize = Number.isInteger(c.bandSize) && c.bandSize > 0 ? c.bandSize : BAND_SIZE;
      let left = done;
      for (let a = c.firstUnit; a <= c.lastUnit && rows.length < WALK_CAP; a += bandSize) {
        const b = Math.min(a + bandSize - 1, c.lastUnit);
        const n = b - a + 1;
        const d = Math.min(left, n);
        left -= d;
        rows.push({ key: `${c.id}:${a}-${b}`, chainId: c.id,
          label: a === b ? `${word} ${a}` : `${word}s ${a}–${b}`, sessions: n, done: d });
      }
    }
  }
  return rows;
}

// Per-row projected finish dates from the SAME week-walk as projectFinish.
// INVARIANT (precise): the last unfinished row WITH SESSIONS DEFINED
// (sessions > 0) lands on exactly projectFinish's date (unit-pinned) — the
// breakdown can never contradict the card's headline. 0-session placeholder
// rows (a chapter waiting for its counts) pass through with finish null and
// are EXCLUDED from that contract, so a consumer must scan with
// `reverse().find(r => !r.complete && r.sessions > 0)`, never a bare
// `!r.complete` — the bare form can land on a trailing placeholder instead
// of the real last row. A row's finish (when set) is the Sunday of the week
// its cumulative remaining sessions are covered.
function chainTimeline(act, fromDate, plan, horizon = 300) {
  const rows = timelineRows(act).map(r =>
    ({ ...r, complete: r.sessions > 0 && r.done >= r.sessions, finish: null }));
  const targets = [];                 // cumulative remaining sessions per row
  let cum = 0;
  for (const r of rows) { cum += Math.max(0, r.sessions - r.done); targets.push(cum); }
  if (!cum) return rows;              // nothing left anywhere
  let acc = 0, w = mondayOf(fromDate), i = 0;
  for (let wk = 0; wk < horizon && i < rows.length; wk++) {
    acc += weekCapacity(act, w, plan.periods, plan.parentCycle);
    // A zero-session row (a chapter waiting for its counts, a first-class
    // state in this app) contributes nothing to `targets`, so it shares its
    // target with whichever row precedes it and would otherwise be popped
    // and stamped with THAT row's date. Pass it through untouched instead —
    // finish stays null, the UI shows "—".
    while (i < rows.length && (rows[i].complete || rows[i].sessions === 0 || acc >= targets[i])) {
      if (!rows[i].complete && rows[i].sessions > 0) rows[i].finish = addDays(w, 6);
      i++;
    }
    w = addDays(w, 7);
  }
  return rows;
}

// Actual finish dates recovered from the log: dated 'done' entries per chain,
// replayed in date order — the entry that crosses a row's cumulative session
// boundary dates that row. Rows advanced without log rows (bulk `done` bumps
// from a Claude session) have no entry here; the view shows a bare ✓.
function actualFinishes(act, log) {
  const out = {};
  const byChain = new Map();
  for (const r of timelineRows(act)) {
    if (!byChain.has(r.chainId)) byChain.set(r.chainId, []);
    byChain.get(r.chainId).push(r);
  }
  for (const [chainId, rows] of byChain) {
    const dates = (Array.isArray(log) ? log : [])
      .filter(e => e && e.status === 'done' && e.curriculum === chainId &&
        typeof e.date === 'string' && ISO.test(e.date))
      .map(e => e.date).sort();
    let upto = 0;
    for (const r of rows) {
      upto += r.sessions;
      if (dates.length >= upto) out[r.key] = dates[upto - 1];
    }
  }
  return out;
}

// A plan-vs-now date delta, ± days between a live projected finish and a
// frozen baseline date: within a week either way reads as "on plan" (dates
// wobble by a session or two without meaning anything), otherwise ▲/▼ by the
// week. Shared by the Subjects 📅 Timeline row chip AND the computed pace
// note (planner-v2.8) so a whole-book "ahead/behind" line can never disagree
// with its own per-chapter breakdown — one rule, two renderings. null when
// either date is missing (no baseline set yet, or an unprojectable row).
function planDeltaChip(finishDate, baselineDate) {
  if (!finishDate || !baselineDate) return null;
  const dd = daysBetween(finishDate, baselineDate);        // + = ahead of plan
  const weeks = Math.round(Math.abs(dd) / 7);
  if (Math.abs(dd) <= 7) return { state: 'on', weeks: 0 };
  return { state: dd > 0 ? 'ahead' : 'behind', weeks };
}

// ── Sanitize (mirror of sanitizeEvents philosophy) ──────────
// Every date that a week-walk loop compares against MUST be a real ISO date,
// or `while (w <= badDate)` never terminates. Guard them all here.
const ISO = /^\d{4}-\d{2}-\d{2}$/;
const isISO = s => typeof s === 'string' && ISO.test(s);

// One period, or null if it can't be trusted. `id` is identity: updatePeriod /
// deletePeriod find rows by it, so an id-less row would be uneditable.
const cleanPeriod = p => {
  if (!p || typeof p !== 'object') return null;
  const id = p.id == null ? '' : String(p.id);
  if (!id || !isISO(p.start) || !isISO(p.end) || p.start > p.end) return null;
  if (!PERIOD_TYPES.includes(p.type)) return null;
  return { id, start: p.start, end: p.end, type: p.type,
    ...(p.label ? { label: String(p.label) } : {}) };
};

// v1 → v2: every marked week becomes a 7-day period (Mon..Sun). `light` is gone
// from the model, so those weeks are dropped; `teaching` was never a marking.
const migrateWeeks = weeks => {
  const out = [];
  if (weeks && typeof weeks === 'object')
    for (const [k, v] of Object.entries(weeks))
      if (isISO(k) && v && PERIOD_TYPES.includes(v.type))
        out.push({ id: `w-${k}`, start: k, end: addDays(k, 6), type: v.type,
          ...(v.label ? { label: String(v.label) } : {}) });
  return out;
};

function sanitizePlan(raw) {
  const r = raw && typeof raw === 'object' ? raw : {};
  const out = { ...r };
  out.version = typeof r.version === 'number' ? r.version : 1;
  out.year = r.year && isISO(r.year.start) && isISO(r.year.end)
    ? r.year : { label: '2026-27', start: '2026-08-17', end: '2027-08-31' };
  const pc = r.parentCycle && isISO(r.parentCycle.anchorMonday)
    ? { ...r.parentCycle } : { pattern: '7on7off', anchorMonday: '2026-08-17', confirmed: false };
  if (!isISO(pc.dutyStart)) pc.dutyStart = DEFAULT_DUTY_START;
  out.parentCycle = pc;
  const seen = new Set();
  const periods = [];
  for (const p of [...(Array.isArray(r.periods) ? r.periods : []).map(cleanPeriod).filter(Boolean),
                   ...migrateWeeks(r.weeks)])
    if (!seen.has(p.id)) { seen.add(p.id); periods.push(p); }   // id is identity: no duplicates
  out.periods = sortPeriods(periods);
  delete out.weeks;
  out.activities = (Array.isArray(r.activities) ? r.activities : [])
    .filter(a => a && typeof a === 'object' && a.id && a.type)
    .map(a => {
      // `id` is required: togglePaced records it in the log and finds the
      // curriculum by it on uncheck. An id-less entry would break that identity.
      const o = { ...a, chain: Array.isArray(a.chain)
          ? a.chain.filter(c => c && c.pattern && c.id).map(c => {
              const cc = { ...c, done: Math.max(0, c.done || 0) };
              // bandSize is a DISPLAY knob for timelineRows: a non-positive or
              // non-integer value would either loop forever or misdraw bands,
              // so an invalid one is dropped rather than carried through —
              // timelineRows then falls back to BAND_SIZE, same as if it were
              // never set.
              if ('bandSize' in cc && !(Number.isInteger(cc.bandSize) && cc.bandSize > 0))
                delete cc.bandSize;
              return cc;
            })
          : [] };
      if (o.goal && !isISO(o.goal.finishBy)) delete o.goal;
      // Baseline (Subjects 📅 Timeline): rebuild to exactly {setOn, rows} or
      // drop it — a corrupt baseline must degrade to "no plan yet", never
      // corrupt the activity or crash a date compare.
      if ('baseline' in o) {
        const b = o.baseline, rows = b && typeof b === 'object' ? b.rows : null;
        const ok = b && isISO(b.setOn) && rows && typeof rows === 'object' &&
          !Array.isArray(rows) && Object.values(rows).every(isISO);
        if (ok) o.baseline = { setOn: b.setOn, rows: { ...rows } };
        else delete o.baseline;
      }
      return o;
    });
  out.log = (Array.isArray(r.log) ? r.log : [])
    .filter(e => e && isISO(e.date) && e.status && (e.activityId || e.eventId));
  out.overrides = (Array.isArray(r.overrides) ? r.overrides : [])
    .filter(o => o && isISO(o.date) && o.action);
  return out;
}

const serializePlan = p => JSON.stringify(p);

// ── Concurrent-write merge (server side) ────────────────────
// Two writers share one blob: this browser and the Telegram bot. A save carries
// the `savedAt` of the blob it was edited on top of (`base`); when KV has moved
// on since, api/plan-save calls this instead of blind last-write-wins.
//
// It is an APPEND union, deliberately narrow: rows present in `current` but
// absent from `incoming` are carried over, because in practice both writers
// only ever ADD — a tap logs a row, the bot writes a one-off. Nothing else is
// reconciled: `incoming` wins outright on activities, periods, parentCycle and
// every other field, since those are edited in one place at a time.
//
// KNOWN LIMIT — deletion resurrection: an untick (log splice) or a deleted
// override that races another writer's save comes back, because "absent from
// incoming" cannot tell "they deleted it" from "they never saw it". The family
// re-taps; nothing is lost, something is restored. That trade is deliberate:
// losing a logged session is silent, an unexpected ✓ is visible. See AGENTS.md.
function mergePlanWrites(current, incoming) {
  if (!incoming || typeof incoming !== 'object') return incoming;
  if (!current || typeof current !== 'object') return incoming;

  // An override written by the bot has an id; one hand-written by a script may
  // not, so fall back to the shape of the row itself.
  const ovKey = o => (o && o.id != null && o.id !== ''
    ? `id:${o.id}`
    : `fp:${o?.date}|${o?.action}|${o?.start}|${o?.end}|${o?.name}`);
  // One status per thing per day is the log's own invariant (logTimed replaces
  // in place), so (date, owner) is the row's identity.
  const logKey = e => `${e?.date}|${e?.eventId || e?.activityId || ''}`;

  const inOv = Array.isArray(incoming.overrides) ? incoming.overrides : [];
  const curOv = Array.isArray(current.overrides) ? current.overrides : [];
  const inLog = Array.isArray(incoming.log) ? incoming.log : [];
  const curLog = Array.isArray(current.log) ? current.log : [];

  const haveOv = new Set(inOv.map(ovKey));
  const haveLog = new Set(inLog.map(logKey));
  const addOv = curOv.filter(o => !haveOv.has(ovKey(o)));
  const addLog = curLog.filter(e => !haveLog.has(logKey(e)));
  if (!addOv.length && !addLog.length) return incoming;    // nothing to carry over

  const out = { ...incoming, overrides: [...inOv, ...addOv], log: [...inLog, ...addLog] };

  // A paced check advances a curriculum's `done` in the same write that logs
  // it. Re-attaching the row alone would leave the chain one session behind, so
  // each carried-over row replays its own increment. Never mutates `incoming`.
  const bumps = addLog.filter(e => e && e.curriculum);
  if (bumps.length) {
    out.activities = (Array.isArray(incoming.activities) ? incoming.activities : []).map(a => ({ ...a }));
    for (const row of bumps) {
      const act = out.activities.find(a => (row.activityId
        ? a.id === row.activityId
        : Array.isArray(a.chain) && a.chain.some(c => c && c.id === row.curriculum)));
      if (!act || !Array.isArray(act.chain)) continue;
      if (!act.chain.some(c => c && c.id === row.curriculum)) continue;
      act.chain = act.chain.map(c =>
        (c && c.id === row.curriculum ? { ...c, done: (c.done || 0) + 1 } : c));
    }
  }
  return out;
}

// ── Weekly capacity: how many sessions this activity expects in a week ──
// `periods` is the day-precise time-away list — always an array (sanitizePlan
// guarantees it on both load paths); every caller in the app passes plan.periods.
function weekCapacity(act, weekStart, periods, cycle) {
  const r = act.rhythm || {};
  let base = 0;
  if (r.kind === 'daily') base = 7;
  else if (r.kind === 'weekly') base = r.perWeek || 1;
  else if (r.kind === 'cycle') base = isOnWeek(cycle, weekStart) ? (r.perOnWeek ?? 1) : (r.perOffWeek ?? 2.5);
  if (!base) return 0;
  // Sessions per teaching day (default 1). Singapore Math is a tb-wb chain
  // where ONE lesson = TWO sessions (textbook + workbook) and the family does
  // both halves the same day, so its rhythm carries `sessionsPerDay: 2` —
  // without it the walk silently assumed textbook one day, workbook the next
  // and projected the finish ~4 months late (2026-08-30 user report). A
  // non-positive/non-finite value reads as 1, never 0 (a typo must not make a
  // subject unprojectable). Mirrored in aoife-school-bot/lib/compose.py.
  const perDay = Number(r.sessionsPerDay);
  const mult = Number.isFinite(perDay) && perDay > 0 ? perDay : 1;
  return base * mult * effectiveDaysInWeek(act, weekStart, periods) / 7;
}

// Walk weeks forward until remaining sessions are covered. null = can't project.
function projectFinish(act, fromDate, plan, horizon = 300) {
  const remaining = actRemaining(act);
  if (actTotal(act) === 0) return null;              // unknown counts (waiting for books)
  if (remaining === 0) return { date: fromDate, weeks: 0, done: true };
  let acc = 0, w = mondayOf(fromDate);
  for (let i = 0; i < horizon; i++) {
    acc += weekCapacity(act, w, plan.periods, plan.parentCycle);
    if (acc >= remaining) return { date: addDays(w, 6), weeks: i + 1 };
    w = addDays(w, 7);
  }
  return null;
}

// Hard stop for every week-walk loop (~11.5 years). Belt-and-braces alongside
// sanitizePlan's ISO guards: an unsanitized/hand-built plan must never hang the UI.
const WALK_CAP = 600;

// Minimum sessions per 2-week cycle to hit the goal (counting non-blocked weeks).
function requiredPerCycle(act, fromDate, plan) {
  if (!act.goal?.finishBy) return null;
  const remaining = actRemaining(act);
  let usable = 0, w = mondayOf(fromDate), n = 0;
  while (w <= act.goal.finishBy) {
    if (n++ >= WALK_CAP) break;                      // behave as if the walk ended
    if (weekCapacity(act, w, plan.periods, plan.parentCycle) > 0) usable++;
    w = addDays(w, 7);
  }
  if (!usable) return null;
  return remaining / (usable / 2);
}

// ── Trip impact: finish dates before vs after a drafted period ──
// `draft` may carry the id of the period being edited, in which case it
// REPLACES that period instead of stacking on top of it. Never mutates `plan`.
function tripImpact(plan, draft, fromDate = todayStr()) {
  const base = asPeriods(plan.periods);
  const raw = { ...draft };                          // a new trip has no id yet
  const d = cleanPeriod({ ...raw, id: raw.id || '__draft__',
    type: PERIOD_TYPES.includes(raw.type) ? raw.type : 'travel' });
  const after = d ? sortPeriods([...base.filter(p => p.id !== d.id), d]) : base;
  const fin = (act, periods) => projectFinish(act, fromDate, { ...plan, periods })?.date ?? null;
  return (Array.isArray(plan.activities) ? plan.activities : [])
    .filter(a => a.type === 'paced' && a.status === 'active' && actTotal(a) > 0)
    .map(a => ({ id: a.id, name: a.name || a.id, before: fin(a, base), after: fin(a, after) }));
}

// ── Cycle stats (7-on/7-off activities) ─────────────────────
function cycleBounds(cycle, dateStr) {
  const k = Math.floor(weeksBetween(cycle.anchorMonday, dateStr) / 2);
  const start = addDays(cycle.anchorMonday, k * 14);
  return { start, end: addDays(start, 13) };
}

const countDone = (log, actId, from, to) =>
  log.filter(e => e.activityId === actId && e.status === 'done' && e.date >= from && e.date <= to).length;

function cycleStats(act, dateStr, cycle, log) {
  const { start, end } = cycleBounds(cycle, dateStr);
  const r = act.rhythm || {};
  const targetMin = Number(r.perOnWeek ?? 1) + Math.floor(Number(r.perOffWeek ?? 2.5));
  const targetMax = Number(r.perOnWeek ?? 1) + Math.ceil(Number(r.perOffWeek ?? 2.5));
  const done = countDone(log, act.id, start, end);
  const prev = cycleBounds(cycle, addDays(start, -1));
  const prevDone = countDone(log, act.id, prev.start, prev.end);
  return {
    start, end, done, targetMin, targetMax,
    behind: dateStr >= end && done < targetMin,
    prevBehind: prevDone < targetMin && weeksBetween(cycle.anchorMonday, dateStr) >= 2,
  };
}

// ── Target-count stats (Jiu Jitsu) ──────────────────────────
function targetStats(act, plan, log, dateStr) {
  const { start, end } = plan.year;
  let total = 0, elapsed = 0, w = mondayOf(start), n = 0;
  while (w <= end) {
    if (n++ >= WALK_CAP) break;                      // behave as if the walk ended
    if (awayDaysInWeek(plan.periods, w) <= 3) {      // a teaching week = 4+ plain school days
      total++;
      if (w <= dateStr) elapsed++;
    }
    w = addDays(w, 7);
  }
  const done = log.filter(e => e.activityId === act.id && e.status === 'done').length;
  const expected = total ? Math.floor((act.target || 0) * (elapsed / total)) : 0;
  return { done, target: act.target || 0, expected, behind: Math.max(0, expected - done) };
}

// ── "This week" helpers (the Today card) ────────────────────
// Teaching-week counter, 1-based from year.start. Same definition of a teaching
// week as targetStats: 4+ plain school days, i.e. awayDaysInWeek <= 3. A
// majority-away week is skipped and does NOT advance the count, so the number
// answers "how many real school weeks in", not "how many weeks on the calendar".
// null = the week of `dateStr` is itself majority-away, or sits before the year
// started (the card then omits the line rather than printing something false).
function teachingWeekNumber(plan, dateStr) {
  const start = plan?.year?.start, end = plan?.year?.end;
  if (!isISO(start) || !isISO(dateStr)) return null;
  if (isISO(end) && dateStr > end) return null;   // past the school year: no number
  const target = mondayOf(dateStr);
  let w = mondayOf(start), n = 0, guard = 0;
  if (target < w) return null;
  while (w <= target) {
    if (guard++ >= WALK_CAP) return null;         // malformed year: no number at all
    const teaching = awayDaysInWeek(plan?.periods, w) <= 3;
    if (teaching) n++;
    if (w === target) return teaching ? n : null;
    w = addDays(w, 7);
  }
  return null;
}

// Consecutive-day run of `done` entries for one activity, ending at `today` —
// or at YESTERDAY when today isn't ticked yet, so a morning before the day's
// work never reads as a broken streak.
// An away day with no entry BRIDGES the run instead of ending it: on travel
// Singapore Math drops to every other day by design, and a rhythm the plan
// itself prescribes must not cost Aoife her streak. A plain (not-away) missed
// day ends it outright.
// The bridge is BOUNDED at MAX_BRIDGE consecutive missed away days — one
// every-other-day gap plus a day of slack. Unbounded, a 5-week Dhaka trip with
// nothing logged would still be advertising a streak earned before the flight,
// which is a lie the fire emoji makes worse. Any `done` day resets the count.
const MAX_BRIDGE = 2;
function dailyStreak(log, actId, periods, today) {
  const done = new Set();
  for (const e of Array.isArray(log) ? log : [])
    if (e && e.activityId === actId && e.status === 'done' && isISO(e.date)) done.add(e.date);
  if (!done.size || !isISO(today)) return 0;
  let d = today, n = 0, bridged = 0;
  for (let i = 0; i < WALK_CAP * 7; i++) {        // same belt-and-braces cap as the week walks
    if (done.has(d)) { n++; bridged = 0; }
    else if (dayAway(periods, d)) {
      if (bridged >= MAX_BRIDGE) break;           // the trip has swallowed the run
      bridged++;                                  // an away today spends bridge like any other
    }
    else if (d !== today) break;                  // a plain missed day ends the run
    // else: today itself, still unticked this morning — no cost, no credit
    d = addDays(d, -1);
  }
  return n;
}

// ── Core attendance: template sessions expected vs logged done ──
// The Year view's core rows answer "how much of this subject's regular week
// actually happened". Both halves are counted from primary data — the template
// and the log — never from a denormalized counter:
//   expected = the category's template events whose weekday falls on a day of
//              this week that is NOT away and NOT cancelled by a `skip`
//              override. A fully-away week therefore expects nothing, which is
//              what stops a trip from reading as a wall of missed sessions.
//   done     = log rows dated Mon..Sun with status 'done' whose eventId is one
//              of those template events. A dated one-off (`action:'add'`) logs
//              against its OWN id, so it can never inflate a template's count.
// `done` is deliberately NOT filtered by away day: work the family did anyway
// on a travel day is work, and the kinder failure mode is to credit it (same
// reasoning as dailyStreak's away-day bridge). The cost is that `done` can
// exceed `expected`, which the Year view reads as a full week — correct — and
// that a WHOLLY away week with sessions logged still shows expected 0. That
// last case is unreachable from the app (the Today view shows no timed blocks
// on an away day, so there is nothing to tap) and is accepted.
// `plan` is the whole blob rather than three arguments: periods, overrides and
// log are always read together here, and splitting them only invited a caller
// to forget one (an omitted `overrides` silently over-counts `expected`).
function weekAttendance(events, plan, weekStart, cat) {
  // A null category must match NOTHING. `e.cat === cat` would otherwise let
  // `undefined === undefined` pair a category-less caller with the corrupt
  // {id:'e999'} record the live blob still carries — the same trap that made
  // today.js's statusOf tick unrelated blocks (see its `it.activityId != null`).
  if (cat == null) return { expected: 0, done: 0 };
  const evs = (Array.isArray(events) ? events : []).filter(e =>
    e && e.cat === cat && Number.isInteger(e.day) && e.day >= 0 && e.day <= 6);
  const overrides = Array.isArray(plan?.overrides) ? plan.overrides : [];
  const log = Array.isArray(plan?.log) ? plan.log : [];
  const ids = new Set(evs.map(e => e.id));
  let expected = 0;
  for (const e of evs) {
    const date = addDays(weekStart, e.day);
    if (dayAway(plan?.periods, date)) continue;
    if (overrides.some(o => o && o.action === 'skip' && o.date === date && o.eventId === e.id)) continue;
    expected++;
  }
  const end = addDays(weekStart, 6);
  const done = log.filter(x => x && x.status === 'done' && x.eventId != null &&
    ids.has(x.eventId) && x.date >= weekStart && x.date <= end).length;
  return { expected, done };
}

// ── Clash detection over template events ────────────────────
const findClashes = (events, slot) =>
  events.filter(e => e.day === slot.day && e.start < slot.end && e.end > slot.start);

function freeSlots(events, day, dur, count = 3) {
  const out = [];
  for (let s = 9; s <= 17 - dur && out.length < count; s += 0.5)
    if (!findClashes(events, { day, start: s, end: s + dur }).length) out.push(s);
  return out;
}

const doneOn = (log, actId, dateStr) =>
  log.some(e => e.activityId === actId && e.date === dateStr && e.status === 'done');

/* ── js/plan/mday.js ── */
// mday.js — the ONE engine behind the /m PWA page and the Scriptable widget.
// PURE: no DOM, no fetch, no globals, no localStorage. Node-testable in
// isolation (tests/plan-mday.test.mjs). today.js's `timedFor`/`statusOf`/
// `dailyVisible` are thin wrappers around this module's `buildTimed`/
// `statusOfTimed`/`dailyVisible` — ONE implementation, so the desktop Today
// view and the phone app can never silently disagree about what "today"
// looks like.
//
// Emoji map is a straight port of aoife-school-bot/lib/compose.py's
// EMOJI_MAP (keyed off a template event's `cat` or an activity's own `id`);
// the tb-wb daily half/done/missed logic mirrors that file's `item_status`
// exactly, with one addition the bot doesn't need: a `half` status (only the
// textbook half of a lesson logged today) so the phone checkbox can show an
// amber in-between state instead of collapsing it into "nothing logged yet".



// ── Emoji map (port of the bot's EMOJI_MAP) ─────────────────
const EMOJI_MAP = {
  quran: '📖', ruhamah: '✏️', hala: '🕌', art: '🎨', barakot: '🏠',
  geography: '🌍', science: '🔬', jj: '🥋', loe: '📚', singapore: '➗',
};
const EMOJI_FALLBACK = '📌';
const emojiFor = key => (key != null && EMOJI_MAP[key]) || EMOJI_FALLBACK;

// ── Subject color dots (Subjects tab + Year) ────────────────
const SUBJECT_COLORS = { singapore: '#e8834a', loe: '#5ea3f2', geography: '#4cc9b0' };
const SUBJECT_COLOR_NEUTRAL = '#9aa0b4';
const colorFor = id => SUBJECT_COLORS[id] || SUBJECT_COLOR_NEUTRAL;

const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const catLabelDefault = cat => CATS[cat]?.label || 'Event';

// A chain name like "3A Ch 1 · Numbers to 10,000" — the part the family
// actually calls the chapter is what comes before the em-dash-style "·".
// Mirrors subjects.js's own shortChainName (kept in sync deliberately: same
// idea, two small pure helpers, not worth a shared import for one line).
const shortChainName = c => String(c?.name || '').split('·')[0].trim();

// ── dailyVisible (moved from today.js — today.js re-exports this) ──
// A daily (no-time-slot) activity shows on a normal day; on a travel-type
// away day only if it doesn't pause for travel; never on an off-type day.
function dailyVisible(act, status) {
  if (!status.away) return true;
  if (status.type === 'off') return false;
  return (act.travel?.mode || 'pause') !== 'pause';
}

// ── Timed blocks for a date (moved from today.js's timedFor) ───────
// `nameForEvent` defaults to a catLabels-UNAWARE fallback (this module never
// sees the store's catLabels renames — it only takes plain `events`); a
// caller that has catLabels (today.js's evLabel, or js/m.js) may pass its
// own resolver and get byte-identical names to the rest of the app. Order:
// template events for the weekday, then on-grid activity slots, then `add`
// overrides, minus anything `skip`ped — same three-source union + skip
// filter as the original, sorted by start.
function buildTimed(dateStr, events, plan, nameForEvent = ev => ev.name || catLabelDefault(ev.cat)) {
  const d = dayIdx(dateStr);
  const activities = plan?.activities || [];
  const overrides = plan?.overrides || [];
  const items = [];
  for (const ev of (events || []).filter(e => e && e.day === d))
    items.push({ key: `ev:${ev.id}`, kind: 'timed', eventId: ev.id, activityId: undefined,
      cls: okCls(CATS[ev.cat]?.cls), name: nameForEvent(ev) || catLabelDefault(ev.cat),
      emoji: emojiFor(ev.cat), start: ev.start, end: ev.end, note: ev.note || '' });
  for (const a of activities.filter(a => a && a.status === 'active' && a.onGrid))
    for (const s of a.slots || [])
      if (s && s.day === d) {
        const cur = currentCur(a);
        items.push({ key: `act:${a.id}`, kind: 'timed', eventId: undefined, activityId: a.id,
          cls: okCls(a.cls), name: a.name, emoji: emojiFor(a.id), start: s.start, end: s.end,
          note: cur && nextSession(cur) ? nextSession(cur).label : '' });
      }
  for (const [i, o] of overrides.entries())
    if (o && o.date === dateStr && o.action === 'add') {
      const a = activities.find(x => x.id === o.activityId);
      items.push({ key: `ov:${o.id || i}`, kind: 'timed', eventId: o.id || undefined,
        activityId: o.activityId, cls: okCls(a?.cls),
        name: o.name || (a?.name || 'Extra') + ' · makeup', emoji: emojiFor(a?.id),
        start: o.start, end: o.end, note: o.note && o.note !== o.name ? o.note : '' });
    }
  const skips = new Set(overrides
    .filter(o => o && o.date === dateStr && o.action === 'skip')
    .map(o => o.eventId || `act:${o.activityId}`));
  return items.filter(it => !skips.has(it.eventId) && !skips.has(it.key))
    .sort((a, b) => a.start - b.start);
}

// ── Logged status for one timed item (moved from today.js's statusOf) ──
// A non-null key is REQUIRED to match (see today.js's own comment on this
// trap: keyless items must never cross-match on `undefined === undefined`).
function statusOfTimed(plan, dateStr, it) {
  return (plan?.log || []).find(e => e && e.date === dateStr &&
    (it.eventId ? e.eventId === it.eventId
                : it.activityId != null && e.activityId === it.activityId && e.timed))?.status;
}

// ── Daily (no-slot) status: port of the bot's item_status, tb-wb half ──
// A tb-wb daily needs BOTH the textbook and workbook session of the SAME
// lesson logged TODAY before it reads 'done'; one half alone reads 'half'
// (the one addition over the bot, which just leaves it unanswered — see the
// module header). A marker row (a missed/partial entry, or ANY 'done' row
// with no curriculum — a plain daily bump) settles the day outright, same
// priority order as compose.py's item_status. A trailing review/test
// session (past the paired lesson sessions) is self-contained and reads
// 'done' alone, exactly like the bot.
function dailyStatus(act, log, dateStr) {
  const entries = (Array.isArray(log) ? log : []).filter(e =>
    e && e.date === dateStr && e.activityId === act?.id && !e.timed && !e.eventId);
  if (!entries.length) return undefined;
  const marker = entries.find(e => e.status !== 'done' || !e.curriculum);
  if (marker) return marker.status;
  const cur = (act.chain || []).find(c => c && c.id === entries[0].curriculum);
  if (!cur || cur.pattern !== 'tb-wb') return 'done';
  const sessionsToday = entries
    .filter(e => e.status === 'done' && typeof e.session === 'number')
    .map(e => e.session).sort((a, b) => a - b);
  if (!sessionsToday.length) return undefined;
  const latest = sessionsToday[sessionsToday.length - 1];
  const paired = (cur.lessons || 0) * 2;
  if (latest >= paired) return 'done';               // trailing test/review: self-contained
  const latestLesson = Math.floor(latest / 2);
  const count = sessionsToday.filter(s => Math.floor(s / 2) === latestLesson).length;
  return count >= 2 ? 'done' : 'half';
}

function noteForDaily(cur) {
  if (!cur) return '';
  const ns = nextSession(cur);
  if (!ns) return '';
  const prefix = cur.pattern === 'tb-wb' ? shortChainName(cur) : '';
  return prefix ? `${prefix} · ${ns.label}` : ns.label;
}

// ── dayItems: the whole day's list, timed first then no-slot dailies ──
// `nameForEvent` (see buildTimed) is optional and passed straight through —
// a caller with catLabels renames (js/m.js, the widget) can get the SAME
// renamed names the desktop Today view shows; without it the plain
// CATS-default label is used, same as before this parameter existed.
function dayItems(dateStr, events, plan, nameForEvent) {
  const status = dayStatus(plan?.periods, dateStr);
  const timed = status.away ? [] : buildTimed(dateStr, events, plan, nameForEvent)
    .map(it => ({ ...it, status: statusOfTimed(plan, dateStr, it) }));
  const dailies = (plan?.activities || []).filter(a =>
    a && a.status === 'active' && a.type === 'paced' && !a.onGrid && dailyVisible(a, status));
  const dailyItems = dailies.map(a => {
    const cur = currentCur(a);
    return { key: `act:${a.id}`, kind: 'daily', eventId: undefined, activityId: a.id,
      name: a.name || a.id, emoji: emojiFor(a.id), note: noteForDaily(cur),
      status: dailyStatus(a, plan?.log, dateStr) };
  });
  return [...timed, ...dailyItems];
}

// ── dayHeader: date label, Mama work/home, away banner ──────
const awayLabelFor = status => {
  const l = String(status.label || '').replace(/[✈⏸]/g, '').trim();
  return l || (status.type === 'off' ? 'Off' : 'Time away');
};

function dayHeader(dateStr, plan) {
  const idx = dayIdx(dateStr);
  const DAYS_SHORT = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const d = s2d(dateStr);
  const dateLabel = `${DAYS_SHORT[idx]} ${MON[d.getMonth()]} ${d.getDate()}`;
  const hasCycle = (plan?.activities || []).some(a => a && a.status === 'active' && a.rhythm?.kind === 'cycle');
  const mama = hasCycle ? (isWorkDay(plan.parentCycle, dateStr) ? 'work' : 'home') : null;
  const status = dayStatus(plan?.periods, dateStr);
  const away = status.away ? { type: status.type, label: awayLabelFor(status) } : null;
  return { dateLabel, mama, away };
}

// ── nowBlock: the current timed item, or the next one, or "day done" ──
function nowBlock(dateStr, items, hourFloat) {
  const timed = (items || []).filter(it => it.kind === 'timed' && it.start != null && it.end != null);
  const current = timed.find(it => hourFloat >= it.start && hourFloat < it.end);
  if (current) return { state: 'now', item: current,
    minutesLeft: Math.max(0, Math.round((current.end - hourFloat) * 60)) };
  const next = timed.filter(it => it.start > hourFloat).sort((a, b) => a.start - b.start)[0];
  if (next) return { state: 'next', item: next,
    minutesUntil: Math.max(0, Math.round((next.start - hourFloat) * 60)) };
  const left = (items || []).filter(it => !it.status).length;
  return { state: 'after', item: null, left };
}

// ── subjectCards: one card per PACED subject, in SUBJECT_ORDER ──
// Planned/parked subjects come through too (status carried on the card so
// the page can dim them), but only an ACTIVE subject gets a projected
// finish/delta — projecting a date for a subject that hasn't started yet
// would be fiction (same rule subjects.js's paceLine already applies).
function subjectCards(plan, dateStr) {
  const acts = (plan?.activities || []).filter(a => a && a.type === 'paced');
  return [...acts].sort(compareSubjects).map(a => {
    const lt = lessonTotals(a);
    const pct = lt.total ? Math.round((lt.done / lt.total) * 100) : 0;
    const cur = currentCur(a);
    const ns = cur ? nextSession(cur) : null;
    const isTbWb = cur?.pattern === 'tb-wb';
    let chapterLabel = null, chapterDone = null, chapterSessions = null;
    if (isTbWb) {
      const lessons = Math.max(0, cur.lessons || 0);
      const done = Math.min(Math.max(0, cur.done || 0), lessons * 2);
      chapterLabel = cur.name || cur.id;
      chapterDone = Math.floor(done / 2) + (done % 2 ? 0.5 : 0);
      chapterSessions = lessons;
    }
    let finish = null, delta = null;
    if (a.status === 'active' && actTotal(a) > 0) {
      const fin = projectFinish(a, dateStr, plan);
      if (fin) {
        finish = fin.date;
        const rows = chainTimeline(a, dateStr, plan);
        const curRow = [...rows].reverse().find(r => !r.complete && r.sessions > 0);
        const base = a.baseline?.rows;
        delta = curRow ? planDeltaChip(curRow.finish, base ? base[curRow.key] : null) : null;
      }
    }
    const weekStart = mondayOf(dateStr), weekEnd = addDays(weekStart, 6);
    const sessionsThisWeek = (Array.isArray(plan?.log) ? plan.log : []).filter(e =>
      e && e.activityId === a.id && e.status === 'done' && e.date >= weekStart && e.date <= weekEnd).length;
    return {
      id: a.id, name: a.name || a.id, color: colorFor(a.id), status: a.status,
      lessonsDone: lt.done, lessonsTotal: lt.total, pct, finish, delta,
      streak: dailyStreak(plan?.log, a.id, plan?.periods, dateStr),
      chapterLabel, chapterDone, chapterSessions,
      nextLabel: ns ? ns.label : null, isTbWb, sessionsThisWeek,
    };
  });
}

// ── widgetModel: the exact strings the Scriptable widget renders ────
// Times as h:mm, no am/pm (mirror of the bot's fmt_hm morning-preview
// style — mornings read like 24h without the suffix; afternoon hours are
// 12-hour, same as the bot).
function fmtHM(hour) {
  let hh = Math.floor(hour), mm = Math.round((hour - hh) * 60);
  if (mm === 60) { hh += 1; mm = 0; }
  const h12 = hh > 12 ? hh - 12 : hh === 0 ? 12 : hh;
  return `${h12}:${String(mm).padStart(2, '0')}`;
}

// "Ruhama — ELA/Math" -> "Ruhama" (year.js's own shortName idiom).
const shortName = n => String(n || '').split('—')[0].trim() || String(n || '').trim();
// A couple of subjects read better by their family nickname than a plain
// truncation ("Singapore Math" -> "Singapore", "Logic of English" -> "LoE");
// anything else falls back to the generic em-dash split.
const WIDGET_NICK = { singapore: 'Singapore', loe: 'LoE' };
const widgetName = it => WIDGET_NICK[it.activityId] || shortName(it.name);

// A daily (no-slot) item has no `start` — only a TIMED item earns the h:mm
// prefix. Widget-model callers hit this for real: a day with 0 or 1 timed
// blocks still has no-slot dailies in items[0]/items[1], and prefixing one
// with a fabricated "12:00" (h=0 -> fmtHM(0)) would invent a time slot that
// does not exist (caught 2026-08-31 verifying the live deploy against a real
// Sunday with only one timed block).
const widgetLabel = it => (it.kind === 'timed' ? `${fmtHM(it.start)} ${widgetName(it)}` : widgetName(it));

function widgetModel(dateStr, events, plan, hourFloat, nameForEvent) {
  const items = dayItems(dateStr, events, plan, nameForEvent);
  const header = dayHeader(dateStr, plan);
  const idx = dayIdx(dateStr);
  const DAYS_SHORT = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const dayLabel = `Today · ${DAYS_SHORT[idx]}`;
  const first = items[0] ? widgetLabel(items[0]) : '';
  let rest = '';
  if (items[1]) {
    const restNames = items.slice(2).map(widgetName);
    rest = widgetLabel(items[1]) + (restNames.length ? ` · then ${restNames.join(' + ')}` : '');
  }
  const done = items.filter(it => it.status === 'done').length;
  const mama = header.mama ? `Mama: ${header.mama} day` : '';
  return { dayLabel, first, rest, done, total: items.length, mama };
}

/* ── scripts/widget-ui.js ── */
// Scriptable rendering layer for Aoife's School medium widget.
// NEVER served or run alone — scripts/build-widget.mjs concatenates this
// after js/model.js + js/plan/model.js + js/plan/mday.js inside one async
// IIFE (Scriptable rejects top-level `await`, so the fetch below only works
// because the whole bundle is wrapped in `(async () => { ... })()`).
// Everything numeric/text comes from mday.js's widgetModel/sanitizePlan/
// todayStr — this file only fetches the two blobs and draws.
/* global Request, ListWidget, FileManager, Script, Color, Font, LinearGradient, config */
/* global sanitizePlan, todayStr, widgetModel, CATS */

const APP_BASE = 'https://aoifes-schedule.vercel.app';

const WCOL = {
  ground: new Color('#12141f'), ink: new Color('#eef0f6'),
  dim: new Color('#eef0f6', 0.58), faint: new Color('#eef0f6', 0.42),
  red: new Color('#f0655a'),
};

const localHourFloat = d => d.getHours() + d.getMinutes() / 60;

async function fetchJSON(url) {
  const req = new Request(url);
  req.timeoutInterval = 15;
  return req.loadJSON();
}

// The day boundary is the PHONE's local date (this is a family-at-home
// surface, not a market one) — todayStr()/localHourFloat() both read the
// device clock, never anything server-supplied.
async function loadData() {
  const fm = FileManager.local();
  const cachePath = fm.joinPath(fm.cacheDirectory(), 'aoife-widget-cache.json');
  try {
    const [schedule, planRaw] = await Promise.all([
      fetchJSON(`${APP_BASE}/api/get`),
      fetchJSON(`${APP_BASE}/api/plan-get`),
    ]);
    const data = { schedule, planRaw };
    fm.writeString(cachePath, JSON.stringify(data));
    return { data, fromCache: false };
  } catch (e) {
    if (fm.fileExists(cachePath))
      return { data: JSON.parse(fm.readString(cachePath)), fromCache: true };
    return { data: null, fromCache: false };
  }
}

async function makeWidget() {
  const w = new ListWidget();
  w.url = `${APP_BASE}/m/`;
  // ListWidget has no real cornerRadius property (iOS rounds the outer shape
  // itself to match the home-screen grid) — set anyway, harmlessly, so the
  // spec's literal "corner radius 24" is on record and a future Scriptable
  // version that DOES honor it picks it up for free.
  w.cornerRadius = 24;
  w.backgroundColor = WCOL.ground;
  const grad = new LinearGradient();
  grad.colors = [new Color('#241f42'), new Color('#12141f')];
  grad.locations = [0, 0.75];
  w.backgroundGradient = grad;
  w.setPadding(16, 18, 14, 18);

  const { data, fromCache } = await loadData();
  if (!data) {
    const t = w.addText("Aoife's School unreachable");
    t.font = Font.semiboldSystemFont(13);
    t.textColor = WCOL.red;
    const s = w.addText('No cache yet — open the app once.');
    s.font = Font.systemFont(11);
    s.textColor = WCOL.dim;
    w.refreshAfterDate = new Date(Date.now() + 30 * 60 * 1000);
    return w;
  }

  const plan = sanitizePlan(data.planRaw);
  const now = new Date();
  const dateStr = todayStr();
  const hourFloat = localHourFloat(now);
  const events = Array.isArray(data.schedule?.events) ? data.schedule.events : [];
  // Same catLabels-aware name resolution the app's own evLabel (js/state.js)
  // uses, so a renamed category (e.g. catLabels.barakot = "Mama Classes")
  // reads the same on the widget as it does on the desktop and /m — CATS
  // comes from js/model.js, bundled ahead of this file by build-widget.mjs.
  const catLabels = data.schedule?.catLabels || {};
  const nameForEvent = ev => ev.name || catLabels[ev.cat] || CATS[ev.cat]?.label || 'Event';
  const m = widgetModel(dateStr, events, plan, hourFloat, nameForEvent);

  const cols = w.addStack();
  cols.spacing = 14;

  const left = cols.addStack();
  left.layoutVertically();
  const lcap = left.addText(m.dayLabel.toUpperCase());
  lcap.font = Font.boldSystemFont(9);
  lcap.textColor = WCOL.faint;
  left.addSpacer(6);
  const lbig = left.addText(m.first || '—');
  lbig.font = Font.boldMonospacedSystemFont(19);
  lbig.textColor = WCOL.ink;
  lbig.lineLimit = 1;
  lbig.minimumScaleFactor = 0.7;
  left.addSpacer(4);
  const lsub = left.addText(m.rest || '');
  lsub.font = Font.regularSystemFont(11);
  lsub.textColor = WCOL.dim;
  lsub.lineLimit = 2;
  lsub.minimumScaleFactor = 0.8;

  cols.addSpacer();          // flexible: pushes DONE to the right column

  const right = cols.addStack();
  right.layoutVertically();
  const rcap = right.addText('DONE');
  rcap.font = Font.boldSystemFont(9);
  rcap.textColor = WCOL.faint;
  right.addSpacer(6);
  const rrow = right.addStack();
  const rbig = rrow.addText(String(m.done));
  rbig.font = Font.boldMonospacedSystemFont(19);
  rbig.textColor = WCOL.ink;
  const rtot = rrow.addText(`/${m.total}`);
  rtot.font = Font.mediumMonospacedSystemFont(14);
  rtot.textColor = WCOL.faint;
  right.addSpacer(4);
  const rsub = right.addText(m.mama || '');
  rsub.font = Font.regularSystemFont(11);
  rsub.textColor = WCOL.dim;
  rsub.lineLimit = 1;
  rsub.minimumScaleFactor = 0.8;

  if (fromCache) {
    w.addSpacer(8);
    const c = w.addText('cached');
    c.font = Font.mediumSystemFont(8);
    c.textColor = WCOL.red;
  }

  w.refreshAfterDate = new Date(Date.now() + 30 * 60 * 1000);
  return w;
}

async function run() {
  const w = await makeWidget();
  if (typeof config !== 'undefined' && config.runsInWidget) Script.setWidget(w);
  else await w.presentMedium();
  Script.complete();
}

run();

})();
