#!/usr/bin/env node
// Bundle the Scriptable widget from the SAME source files the app runs —
// js/model.js + js/plan/model.js + js/plan/mday.js — plus the Scriptable
// glue layer (scripts/widget-ui.js). No day/subject logic is ever hand-copied
// into the widget; this build is the only way m/widget.js changes.
// Run: node scripts/build-widget.mjs
//
// Scriptable's JS engine has no ES module system, so this strips `import`
// statements entirely (after concatenation every named export is already a
// plain top-level declaration in the same scope) and drops the `export `
// keyword from every declaration (the identifier stays defined; only the
// syntax Scriptable can't parse is removed). The whole bundle is wrapped in
// one async IIFE — Scriptable rejects top-level `await`, which widget-ui.js
// needs for its fetches.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';
import { createHash } from 'node:crypto';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
export const SOURCES = ['js/model.js', 'js/plan/model.js', 'js/plan/mday.js', 'scripts/widget-ui.js'];

// Import blocks are single-line (`import { CATS } from '../model.js';`) or
// multi-line destructured (`import {\n  a, b,\n} from './model.js';`); this
// module has no nested braces inside an import, so a non-greedy match from
// the first `{` to the first `}` is safe across both shapes.
const IMPORT_RE = /import\s*\{[\s\S]*?\}\s*from\s*['"][^'"]+['"];?/g;
const EXPORT_RE = /^export\s+(function|const|let|class|async function)/gm;

export function stripModuleSyntax(src) {
  return src.replace(IMPORT_RE, '').replace(EXPORT_RE, '$1');
}

export function buildBundle(readFile = p => readFileSync(join(REPO, p), 'utf8')) {
  const parts = SOURCES.map(rel => ({ rel, src: stripModuleSyntax(readFile(rel)) }));
  const hash = createHash('sha256').update(parts.map(p => p.src).join('\n')).digest('hex').slice(0, 10);
  const bundle = [
    "/* Aoife's School — Scriptable medium-widget bundle. GENERATED by",
    ' * scripts/build-widget.mjs from js/model.js + js/plan/model.js +',
    ' * js/plan/mday.js + scripts/widget-ui.js. NEVER edit this file by hand —',
    ' * edit the sources and rebuild: node scripts/build-widget.mjs',
    ` * build ${hash} */`,
    '(async () => {',
    ...parts.map(p => `/* ── ${p.rel} ── */\n${p.src}`),
    '})();',
    '',
  ].join('\n');
  return { bundle, hash };
}

// Only run the write when invoked directly (`node scripts/build-widget.mjs`),
// not when imported by tests/plan-widget.test.mjs.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { bundle, hash } = buildBundle();
  writeFileSync(join(REPO, 'm', 'widget.js'), bundle);
  console.log(`built m/widget.js (${bundle.length} bytes, build ${hash})`);
}
